feeder: dataset.dataloader_video.BaseFeeder
phase: train
dataset: QSLR2024
# dataset: phoenix14-si5
num_epoch: 25 #40
work_dir: ./work_dir/baseline_vgg16_bn/
batch_size: 1
random_seed: 0
test_batch_size: 4
num_worker: 8 #10
device: 0,1
log_interval: 50
eval_interval: 1
save_interval: 5
# python in default
#evaluate_tool: sclite
loss_weights:
  SeqCTC: 1.0
  # VAC
  # ConvCTC: 1.0
  # Dist: 10.0
#load_weights: ''

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [ 20, 35]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0

model: slr_network.SLRModel
decode_mode: beam
model_args:
  num_classes: 1296
  c2d_type: vgg16_bn #resnet18, mobilenet_v2, squeezenet1_1, shufflenet_v2_x1_0, efficientnet_b1, mnasnet1_0, regnet_y_800mf, vgg16_bn, vgg11_bn, regnet_x_800mf, regnet_x_400mf, densenet121, regnet_y_1_6gf, | mobilenet_v3_small, shufflenet_v2_x1_0, mnasnet1_0, mobilenet_v3_large googlenet
  conv_type: 2
  use_bn: 1
  # SMKD
  share_classifier: False
  weight_norm: False
